#!/usr/bin/env bash
# Set up and run the repo on a local NVIDIA GPU (e.g. RTX PRO Blackwell / sm_120)
# from a VS Code Ubuntu / WSL terminal.
#
# From scratch:
#   git clone https://github.com/Leviathan2006/fno-misspecification-benchmarks.git
#   cd fno-misspecification-benchmarks
#   bash run_local.sh
#
# The datasets are bundled in data/, so nothing is regenerated by default.
set -euo pipefail

PYTHON=${PYTHON:-python3}

echo ">>> [1/4] creating virtual environment (.venv)"
$PYTHON -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate
python -m pip install --upgrade pip wheel

echo ">>> [2/4] installing dependencies"
python -m pip install numpy scipy matplotlib
# Blackwell (sm_120) needs a CUDA 12.8+ build of PyTorch. If training later errors
# with "no kernel image is available for execution on the device", re-run with the
# nightly channel (printed at the end of this script).
python -m pip install torch --index-url https://download.pytorch.org/whl/cu128

echo ">>> [3/4] GPU sanity check"
python - <<'PY'
import torch
print("torch", torch.__version__, "| CUDA build", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("device:", torch.cuda.get_device_name(0),
          "| compute capability", torch.cuda.get_device_capability(0))
else:
    print("WARNING: no GPU visible — will run on CPU")
PY

echo ">>> [4/4] running the paper's method (diffusion-reaction)"
# quick sanity check first, then the full paper-setting run
python run_correction.py --mode all --quick
# known vs misspecified vs corrected at the paper's Table 1 settings
python run_correction.py --mode all

cat <<'MSG'

Done.

Notes:
  * run_correction.py needs no dataset file: it evaluates the manufactured
    diffusion-reaction solution analytically at its own sensor / collocation /
    observation points.
  * The other three benchmarks have data generators but the method is not yet
    implemented for them. To build their data at the paper's sizes:
        python datasets/burgers.py --n_train 2000 --n_test 100
        python datasets/cavity_flow.py --n_train 1000 --n_test 100 --N 101
        python datasets/hyperelastic.py --n_train 200 --n_test 100
    (the cavity LBM and hyperelastic FEM are CPU-bound -- hours, not minutes).
  * If you saw an sm_120 / "no kernel image" error, reinstall torch with:
        pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu128
MSG
